### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by squirrelkiller** [BuiltBrokenModding/SBM-woodenShears#1]
[crash-2016-09-11_11.35.17-server.txt](https://github.com/BuiltBrokenModding/SBM-woodenShears/files/466066/crash-2016-09-11_11.35.17-server.txt)

**Comment by dmodoomsirius** [comment]
We are aware I haven't pushed the fix to curseforge yet. I'll do it as soon as I am able to. 

Thanks,
Dmodoomsirius

**Comment by dmodoomsirius** [comment]
Might be Missing a check. I'll look at it soon.

**Comment by kolatra** [comment]
Fixed.
