### ISSUE TITLE
[1.14/1.15] Can't shear leaves properly, and other issues related to loot tables

### ISSUE THREAD

**Issue by coderbot16** [BuiltBrokenModding/SBM-woodenShears#10]
Vanilla loot tables are hardcoded to check for `minecraft:shears`, so using wooden shears on many vanilla blocks such as leaves or tall grass will drop seeds and saplings instead. Forge might need to add a `forge:shears` tag to fix this.

**Comment by DarkGuardsman** [comment]
Fixed in 1.15.2 release https://www.curseforge.com/minecraft/mc-mods/sbm-wooden-shears/files/2954828

Might back port to 1.14 if there is enough demand
