### ISSUE TITLE
[1.14/1.15] Shears don't have a dispenser behavior

### ISSUE THREAD

**Issue by coderbot16** [BuiltBrokenModding/SBM-woodenShears#11]
When you try to put wooden shears in a dispenser, the dispenser will shoot the shears out instead of actually shearing the sheep/mooshrooms/snow golems.

**Comment by bl4ckscor3** [comment]
Fixed in 1.17+ by cc66082992390ddd063d7a69188e30ea3da0d4f1 and 0e7e484262097129a81f08fee4ebbf017198429f.
