### ISSUE TITLE
Add: Durability config per wood type

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/SBM-woodenShears#6]
Requested by a user on curse

**Comment by bl4ckscor3** [comment]
Added for 1.12.2 (23192946a818924bd2306c2e7bc7bb794ff90096), 1.11.2 (f1c79a6349457ae7c8ed47c48d50f57a44ea6b8a), 1.10.2 (1029a07be5c3107a3bbb6d62df5bd4a98348be93), 1.8.9 (12903215acd5d1ad0c63edfa69919fc4762a8fdf) and 1.7.10 (e2f711795ca84e1515baa1a93926f98ae69354ed).

EDIT: 1.9.4, too (12fe7ac34afa099505b5748f7100b81e4ebd9570).

**Comment by DarkGuardsman** [comment]
good work
